version: 2

jobs:
  # Terraform init and plan
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd /tmp/project/environ/dev/
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .   
  # Terraform apply plan; to deploy infrastructure
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform
          command: |
            cd /tmp/project/environ/dev/
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .
  # Terraform destroy plan
  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform create destroy plan
          command: |
            cd /tmp/project/environ/dev/
            terraform plan -destroy -out tfdestroy
          root: /tmp/project
          paths:
            - .
  # Terraform apply destroy plan; to teardown infrastructure
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform destroy
          command: |
            cd /tmp/project/environ/dev/
            terraform apply -auto-approve tfdestroy
  
  build_deploy_app:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: build and deploy to ecr
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: chmod +x ./scripts/deploy.sh
      - run: ./scripts/deploy.sh airflow-dev


workflows:
  version: 2
  # Deploy infrastructure to AWS Environment
  App_Infrastructure_plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          # description: hold apply for the plan #
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - build_deploy_app:
          requires:
            - apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
 