version: '2.1'
orbs:
  terraform: circleci/terraform@x.y.z
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: /environ/dev
      - terraform/validate:
          path: /environ/dev
      - terraform/fmt:
          path: /environ/dev
      - terraform/plan:
          path: /environ/dev
      - terraform/apply:
          path: /environ/dev
      - terraform/destroy:
          path: /environ/dev
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle