version: '2.1'
orbs:
  terraform: 'circleci/terraform@dev:alpha'
jobs:
  single-job-lifecycle:
    working_directory: ~/src
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ~/src/environ/dev
      - terraform/validate:
          path: ~/src/environ/dev
      - terraform/fmt:
          path: ~/src/environ/dev
      - terraform/plan:
          path: ~/src/environ/dev
      - terraform/apply:
          path: ~/src/environ/dev
      - terraform/destroy:
          path: ~/src/environ/dev
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle